parameters:
  twig.config:
    debug: false
    auto_reload: false
    cache: true
  http.response.debug_cacheability_headers: false

services:
  cache.backend.apcu:
    class: Drupal\Core\Cache\ApcuBackendFactory
    arguments: ['@cache_tags_provider.container']
