global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nginx"
    metrics_path: /nginx_status
    static_configs:
      - targets: ["nginx:80"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
