{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drupal-boilerplate.secretName" . }}
  labels:
    {{- include "drupal-boilerplate.labels" . | nindent 4 }}
type: Opaque
stringData:
  DRUPAL_HASH_SALT: {{ .Values.secrets.hashSalt | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  S3_ACCESS_KEY_ID: {{ .Values.secrets.s3AccessKeyId | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.secrets.s3SecretAccessKey | quote }}
{{- end }}
